name: Android build

on: 
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      JVM_OPTS: -Xmx6G
      VCPKG_ROOT: /usr/local/share/vcpkg

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - uses: hendrikmuhs/ccache-action@v1.2

      - name: Restore Gradle Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/
            ${{ env.VCPKG_ROOT }}/installed
            ${{ env.VCPKG_ROOT }}/packages
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('android/**/*.xml') }}-${{ hashFiles('android/**.java') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}-${{ hashFiles('android/**/*.xml') }}-
            ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}-
            ${{ runner.os }}-gradle-

      - name: Set up build environment
        run: |
          sudo apt-get install -y ninja-build
          vcpkg install boost-system:arm64-android boost-filesystem:arm64-android boost-program-options:arm64-android boost-icl:arm64-android boost-variant:arm64-android openssl:arm64-android zlib:arm64-android

      - name: Compute git short sha
        shell: bash
        run: echo "git_short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Generate Keystore
        run: |
          keytool -genkey -v -keystore /home/runner/keystore.jks \
          -alias vita3k \
          -keyalg RSA \
          -keysize 2048 \
          -validity 10000 \
          -storepass vita3kpass \
          -keypass vita3kpass \
          -dname "CN=Vita3K, OU=Vita3K, O=Vita3K, L=Unknown, S=Unknown, C=US"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true

      - name: Gradle build 64bit release
        env:
          SIGNING_STORE_PATH: "/home/runner/keystore.jks"
          SIGNING_STORE_PASSWORD: "vita3kpass"
          SIGNING_KEY_ALIAS: "vita3k"
          SIGNING_KEY_PASSWORD: "vita3kpass"
        run: |
          bash -c "yes || Yes || true" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null
          mkdir android/assets/data
          cp -r data/image android/assets/data/image
          cp -r lang android/assets
          cp -r vita3k/shaders-builtin android/assets
          export JAVA_HOME=$(echo $JAVA_HOME_17_X64)
          ./gradlew --stacktrace --info --configuration-cache --build-cache --parallel --configure-on-demand assembleRelease

      - name: Rename APK
        run: |
          mv android/build/outputs/apk/release/android-release.apk \
          android/build/outputs/apk/release/vita3k-aarch64-${{ env.git_short_sha }}-release.apk

      - uses: actions/upload-artifact@v4
        with:
          name: vita3k-${{ env.git_short_sha }}-release_arm64.zip
          path: android/build/outputs/apk/release/vita3k-aarch64-${{ env.git_short_sha }}-release.apk          
